### PR TITLE
Fix parsing description for zh_CN

### PR DESCRIPTION
**Pull request by garbear**
Error was:

```
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 29, column 41
```

Related PRs:

https://github.com/kodi-game/kodi-game-scripting/pull/99

### CODE REVIEW

**Comment by garbear** [comment]
@gade01 Can you look into the weblate side? After fixing this, the error is re-synced: https://github.com/kodi-game/game.libretro.gw/commit/e78298bd893cca3a9c172416f45d126b88872354

**Comment by gade01** [comment]
@garbear Thanks for looking into this.
I have fixed it here: https://github.com/kodi-game/game.libretro.gw/commit/6623931513ecf6e19ba30f233a6ec447d5eafee7

**Comment by gade01** [comment]
And it looks like the workflow fixed the addon.xml file here: https://github.com/kodi-game/game.libretro.gw/commit/444e0ee0e7dff66c308b0cdaf8594b2ce2b23f48

**Comment by garbear** [comment]
thanks!

**Comment by garbear** [comment]
I changed the English string to remove the XML encoding, and the workflow is now doing the reverse of https://github.com/kodi-game/game.libretro.gw/commit/444e0ee0e7dff66c308b0cdaf8594b2ce2b23f48: https://github.com/kodi-game/game.libretro.gw/commit/f2264d908b3f79338006758eea1c89dd4923f29d

**Pull request closed without merging**
